objects/SU_Search_Entity__mdt/SU_Search_Entity__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Object will be used for Search Utility LWC Component , which is a reusable asset for search. Use this object to define the search component paramaters/placeholders with their properties like Name,API Name etc to generate a where statement to be utilized further for Dynamic queries.</description>
    <label>Search Entity</label>
    <pluralLabel>Search Entities</pluralLabel>
</CustomObject>

objects/SU_Search_Entity__mdt/fields/SU_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SU_Api_Name__c</fullName>
    <description>API Name of the Field</description>
    <inlineHelpText>API Name of the Field</inlineHelpText>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Feature__c.field-meta.xml
<CustomField>
    <fullName>SU_Feature__c</fullName>
    <description>Feature in which this property will be used</description>
    <inlineHelpText>Feature in which this property will be used</inlineHelpText>
    <label>Feature</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Re-Org Search</fullName>
                <default>true</default>
                <label>Re-Org Search</label>
            </value>
            <value>
                <fullName>Transfer-In Search</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>SU_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Active if checked</description>
    <inlineHelpText>Active if checked</inlineHelpText>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Label__c.field-meta.xml
<CustomField>
    <fullName>SU_Label__c</fullName>
    <description>Label of Search placeholder</description>
    <inlineHelpText>Label of Search placeholder</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Operator__c.field-meta.xml
<CustomField>
    <fullName>SU_Operator__c</fullName>
    <description>Placeholder operator</description>
    <inlineHelpText>Choose the operator using which search parameter will be defined</inlineHelpText>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>EQUALS</fullName>
                <default>true</default>
                <label>EQUALS</label>
            </value>
            <value>
                <fullName>LIKE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Options__c.field-meta.xml
<CustomField>
    <fullName>SU_Options__c</fullName>
    <description>Dropdown Options</description>
    <inlineHelpText>Dropdown Options. Populate only if Type is picklist/dropdown. (separate values using &apos;;&apos; as a separator)</inlineHelpText>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Order__c.field-meta.xml
<CustomField>
    <fullName>SU_Order__c</fullName>
    <description>Order</description>
    <inlineHelpText>Order (Number For E.g : 1) : To define the order of placeholders on UI</inlineHelpText>
    <label>Order</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Required__c.field-meta.xml
<CustomField>
    <fullName>SU_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check for required placeholder</description>
    <inlineHelpText>Check if Placeholder is required on screen</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

objects/SU_Search_Entity__mdt/fields/SU_Type__c.field-meta.xml
<CustomField>
    <fullName>SU_Type__c</fullName>
    <description>Placeholder Type in which it will be visible on UI</description>
    <inlineHelpText>Placeholder Type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Dropdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SU_SearchFormUtilityController.cls
/**
 * @ File Name          : SU_SearchFormUtilityController.cls
 * @ Description        : This Apex class is a Controller for lwc : search form utility
 * @ Author             : Kumar Vijayendra
 * @ Group              : 
 * @ Modification Log   :
 * Ver          Date            Author                 	Modification
 * 1.0      08-07-2024      Kumar Vijayendra            Initial Version
**/
public without sharing class SU_SearchFormUtilityController {
    
    /**
     * @Desciption  : This method is to get the SU Search entitiy Metadata records as per Feature
     * @date        : 2023-10-26
     * @author      : Kumar Vijayendra (vijayendra.pratap@salesforce.com)
     * @Input       : String feature
     * @return      : List<SU_Search_Entity__mdt>
    */
    @AuraEnabled
    public static List<SU_Search_Entity__mdt> getMetadataRecords(String feature) {
        return [SELECT Id, SU_Label__c, SU_Api_Name__c, SU_Required__c, SU_Type__c, SU_Options__c, SU_Operator__c, SU_Order__c,SU_Feature__c  FROM SU_Search_Entity__mdt where SU_Feature__c =: feature and SU_Is_Active__c = true ORDER BY SU_Order__c asc];
    }
}